create table account (active bit not null, created_at datetime(6) not null, record_version bigint not null, updated_at datetime(6), code varchar(30) not null, created_by varchar(50), updated_by varchar(50), name varchar(255) not null, type varchar(255) not null, primary key (code)) engine=InnoDB;
create table audit_logs (created_at datetime(6), id bigint not null auto_increment, action varchar(50) not null, ip_address varchar(50), module varchar(50), user_role varchar(50), username varchar(50) not null, entity_id varchar(100), entity_name varchar(100) not null, user_full_name varchar(100), details TEXT, primary key (id)) engine=InnoDB;
create table brands (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), code varchar(50) not null, created_by varchar(50), updated_by varchar(50), name varchar(150) not null, description TEXT, primary key (id)) engine=InnoDB;
create table categories (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), code varchar(20) not null, created_by varchar(50), updated_by varchar(50), name varchar(100) not null, description TEXT, primary key (id)) engine=InnoDB;
create table credit_notes (amount decimal(38,2) not null, applied_amount decimal(38,2) not null, issue_date date not null, created_at datetime(6), customer_id bigint not null, id bigint not null auto_increment, sales_return_id bigint not null, updated_at datetime(6), status varchar(30) not null, created_by varchar(50), credit_note_number varchar(50) not null, updated_by varchar(50), primary key (id)) engine=InnoDB;
create table credit_allocation (amount decimal(15,2) not null, reversed bit not null, credit_note_id bigint not null, id bigint not null auto_increment, invoice_id bigint not null, primary key (id)) engine=InnoDB;
create table customer_group_mappings (customer_id bigint not null, group_id bigint not null, primary key (customer_id, group_id)) engine=InnoDB;
create table customer_groups (is_active bit not null, assigned_staff_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), group_code varchar(30) not null, created_by varchar(50), updated_by varchar(50), group_name varchar(100) not null, description varchar(255), primary key (id)) engine=InnoDB;
create table customers (credit_limit decimal(38,2) not null, current_balance decimal(38,2) not null, is_active bit not null, created_at datetime(6) not null, customer_group_id bigint, delivery_route_id bigint, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), customer_code varchar(20) not null, phone varchar(30), created_by varchar(50), updated_by varchar(50), contact_person varchar(100), email varchar(100), name varchar(150) not null, address TEXT, primary key (id)) engine=InnoDB;
create table deliveries (end_odometer float(53), scheduled_date date not null, start_odometer float(53), total_amount decimal(12,2), total_invoices_count integer, trip_duration_minutes integer, assistant_staff_id bigint not null, cancellation_date datetime(6), created_at datetime(6) not null, departure_time datetime(6), driver_id bigint not null, id bigint not null auto_increment, record_version bigint not null, return_time datetime(6), route_id bigint, updated_at datetime(6), vehicle_id bigint, warehouse_id bigint, status varchar(30) not null, created_by varchar(50), delivery_number varchar(50) not null, updated_by varchar(50), vehicle_number varchar(50), gps_tracking_code varchar(100), cancellation_reason TEXT, gps_last_location varchar(255), notes TEXT, primary key (id)) engine=InnoDB;
create table delivery_routes (estimated_distance_km float(53), estimated_duration_minutes integer, is_active bit not null, assigned_staff_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), route_code varchar(30) not null, created_by varchar(50), updated_by varchar(50), area varchar(100), delivery_days varchar(100), route_name varchar(100) not null, end_location varchar(150), start_location varchar(150), description TEXT, primary key (id)) engine=InnoDB;
create table document_sequences (year integer not null, created_at datetime(6), current_sequence bigint not null, id bigint not null auto_increment, updated_at datetime(6), prefix varchar(10) not null, document_type varchar(30) not null, primary key (id)) engine=InnoDB;
create table fiscal_year (closed bit not null, fiscal_year integer not null, primary key (fiscal_year)) engine=InnoDB;
create table grn_items (quantity_received decimal(38,2) not null, total_cost decimal(38,2) not null, unit_cost decimal(38,2) not null, created_at datetime(6), grn_id bigint not null, id bigint not null auto_increment, product_id bigint not null, notes varchar(255), primary key (id)) engine=InnoDB;
create table grns (received_date date not null, total_amount decimal(38,2) not null, cancelled_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, purchase_order_id bigint, record_version bigint not null, supplier_id bigint not null, updated_at datetime(6), warehouse_id bigint not null, status varchar(30) not null, created_by varchar(50), grn_number varchar(50) not null, updated_by varchar(50), cancelled_by varchar(100), supplier_invoice_number varchar(100), cancel_reason TEXT, notes TEXT, primary key (id)) engine=InnoDB;
create table gtn_items (quantity_transferred decimal(38,2) not null, unit_cost decimal(38,2) not null, created_at datetime(6), gtn_id bigint not null, id bigint not null auto_increment, product_id bigint not null, notes varchar(255), primary key (id)) engine=InnoDB;
create table gtns (dispatch_date date, receive_date date, created_at datetime(6) not null, destination_warehouse_id bigint not null, id bigint not null auto_increment, record_version bigint not null, source_warehouse_id bigint not null, updated_at datetime(6), status varchar(30) not null, created_by varchar(50), gtn_number varchar(50) not null, updated_by varchar(50), notes TEXT, primary key (id)) engine=InnoDB;
create table idempotency_record (resource_id bigint, fingerprint varchar(64) not null, request_key varchar(64) not null, primary key (request_key)) engine=InnoDB;
create table invoice_items (cost_price decimal(38,2) not null, discount_amount decimal(38,2) not null, discount_rate decimal(38,2) not null, quantity decimal(38,2) not null, total_price decimal(38,2) not null, unit_price decimal(38,2) not null, created_at datetime(6), id bigint not null auto_increment, invoice_id bigint not null, product_id bigint not null, primary key (id)) engine=InnoDB;
create table invoices (balance_amount decimal(38,2) not null, delivery_date date, discount_amount decimal(38,2) not null, invoice_date date not null, net_total decimal(38,2) not null, paid_amount decimal(38,2) not null, returned_amount decimal(38,2) not null, subtotal decimal(38,2) not null, tax_amount decimal(38,2) not null, tax_rate decimal(38,2) not null, created_at datetime(6) not null, customer_id bigint not null, delivery_id bigint, id bigint not null auto_increment, record_version bigint not null, sales_rep_id bigint, updated_at datetime(6), warehouse_id bigint not null, delivery_status varchar(30), payment_method varchar(30), payment_type varchar(30) not null, status varchar(30) not null, created_by varchar(50), invoice_number varchar(50) not null, updated_by varchar(50), delivery_notes TEXT, notes TEXT, primary key (id)) engine=InnoDB;
create table journal (posting_date date not null, reconciled bit not null, reversed bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, reversal_of bigint, updated_at datetime(6), created_by varchar(50), updated_by varchar(50), description varchar(255) not null, kind varchar(255) not null, source varchar(255) not null, primary key (id)) engine=InnoDB;
create table journal_line (credit decimal(19,2) not null, debit decimal(19,2) not null, id bigint not null auto_increment, journal_id bigint not null, account_code varchar(30) not null, primary key (id)) engine=InnoDB;
create table payment_allocation (amount decimal(15,2) not null, reversed bit not null, created_at datetime(6) not null, id bigint not null auto_increment, invoice_id bigint not null, payment_id bigint not null, record_version bigint not null, updated_at datetime(6), created_by varchar(50), updated_by varchar(50), primary key (id)) engine=InnoDB;
create table payments (amount decimal(15,2) not null, payment_date date not null, created_at datetime(6) not null, customer_id bigint not null, id bigint not null auto_increment, invoice_id bigint, record_version bigint not null, updated_at datetime(6), payment_method varchar(30) not null, payment_type varchar(30), status varchar(30) not null, created_by varchar(50), payment_number varchar(50) not null, updated_by varchar(50), reference_number varchar(100), notes TEXT, primary key (id)) engine=InnoDB;
create table permissions (created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), module varchar(50) not null, name varchar(100) not null, description varchar(255), primary key (id)) engine=InnoDB;
create table prn_items (quantity_returned decimal(38,2) not null, total_cost decimal(38,2) not null, unit_cost decimal(38,2) not null, created_at datetime(6), id bigint not null auto_increment, prn_id bigint not null, product_id bigint not null, reason varchar(255), primary key (id)) engine=InnoDB;
create table prns (return_date date not null, total_amount decimal(38,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, source_grn_id bigint, supplier_id bigint not null, updated_at datetime(6), warehouse_id bigint not null, status varchar(30) not null, created_by varchar(50), prn_number varchar(50) not null, updated_by varchar(50), reason TEXT, primary key (id)) engine=InnoDB;
create table product_staff_quotas (allocated_quantity decimal(12,2) not null, is_active bit not null, sold_quantity decimal(12,2) not null, valid_from date, valid_to date, created_at datetime(6) not null, id bigint not null auto_increment, product_id bigint not null, record_version bigint not null, updated_at datetime(6), user_id bigint not null, warehouse_id bigint, created_by varchar(50), updated_by varchar(50), notes varchar(255), primary key (id)) engine=InnoDB;
create table products (cost_price decimal(38,2) not null, is_active bit not null, min_stock_level integer not null, selling_price decimal(38,2) not null, brand_id bigint, category_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, supplier_id bigint, updated_at datetime(6), warehouse_id bigint, unit_of_measure varchar(20) not null, barcode varchar(50), created_by varchar(50), sku varchar(50) not null, updated_by varchar(50), name varchar(200) not null, description TEXT, primary key (id)) engine=InnoDB;
create table purchase_orders (expected_date date, order_date date not null, total_amount decimal(15,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, supplier_id bigint not null, updated_at datetime(6), warehouse_id bigint not null, created_by varchar(50), updated_by varchar(50), notes TEXT, po_number varchar(255) not null, status varchar(255) not null, terms varchar(255), primary key (id)) engine=InnoDB;
create table purchase_order_item (quantity decimal(15,3) not null, received_quantity decimal(15,3) not null, unit_cost decimal(15,2) not null, id bigint not null auto_increment, product_id bigint not null, purchase_order_id bigint not null, primary key (id)) engine=InnoDB;
create table quotation_items (discount_amount decimal(15,2), discount_rate decimal(5,2), quantity integer not null, total_price decimal(15,2) not null, unit_price decimal(15,2) not null, id bigint not null auto_increment, product_id bigint, quotation_id bigint not null, product_sku varchar(50), product_name varchar(200) not null, primary key (id)) engine=InnoDB;
create table quotations (discount_amount decimal(15,2), quotation_date date not null, subtotal decimal(15,2), tax_amount decimal(15,2), total_amount decimal(15,2) not null, valid_until date, converted_invoice_id bigint, created_at datetime(6) not null, customer_id bigint, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), customer_phone varchar(30), status varchar(30) not null, converted_invoice_number varchar(50), created_by varchar(50), quotation_number varchar(50) not null, updated_by varchar(50), customer_email varchar(100), customer_name varchar(150), notes TEXT, terms TEXT, primary key (id)) engine=InnoDB;
create table refresh_session (expires_at datetime(6) not null, token_version bigint not null, id varchar(255) not null, token_id varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id)) engine=InnoDB;
create table roles (created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), name varchar(50) not null, description varchar(255), primary key (id)) engine=InnoDB;
create table sales_return_items (is_restocked bit not null, quantity decimal(38,2) not null, total_amount decimal(38,2) not null, unit_price decimal(38,2) not null, created_at datetime(6), id bigint not null auto_increment, invoice_item_id bigint, product_id bigint not null, sales_return_id bigint not null, condition_type varchar(30) not null, primary key (id)) engine=InnoDB;
create table sales_returns (refund_amount decimal(38,2) not null, return_date date not null, total_amount decimal(38,2) not null, created_at datetime(6) not null, customer_id bigint not null, id bigint not null auto_increment, invoice_id bigint not null, record_version bigint not null, updated_at datetime(6), warehouse_id bigint not null, return_type varchar(30) not null, status varchar(30) not null, created_by varchar(50), return_number varchar(50) not null, updated_by varchar(50), reason TEXT, primary key (id)) engine=InnoDB;
create table stock_adjustment_items (difference_quantity decimal(38,2) not null, physical_quantity decimal(38,2) not null, system_quantity decimal(38,2) not null, unit_cost decimal(38,2) not null, adjustment_id bigint not null, created_at datetime(6), id bigint not null auto_increment, product_id bigint not null, reason varchar(255), primary key (id)) engine=InnoDB;
create table stock_adjustments (adjustment_date date not null, approved_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), warehouse_id bigint not null, status varchar(30) not null, adjustment_number varchar(50) not null, approved_by varchar(50), created_by varchar(50), updated_by varchar(50), reason TEXT, primary key (id)) engine=InnoDB;
create table stock_balances (quantity decimal(38,2) not null, reserved_quantity decimal(38,2) not null, created_at datetime(6), id bigint not null auto_increment, product_id bigint not null, updated_at datetime(6), version bigint not null, warehouse_id bigint not null, primary key (id)) engine=InnoDB;
create table stock_movements (balance_after decimal(38,2) not null, balance_before decimal(38,2) not null, quantity decimal(38,2) not null, unit_cost decimal(38,2) not null, created_at datetime(6), created_by_user_id bigint, id bigint not null auto_increment, product_id bigint not null, warehouse_id bigint not null, movement_type varchar(30) not null, reference_type varchar(50) not null, reference_number varchar(100) not null, notes varchar(255), primary key (id)) engine=InnoDB;
create table supplier_payment (amount decimal(15,2) not null, payment_date date not null, reversed bit not null, created_at datetime(6) not null, grn_id bigint not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), created_by varchar(50), updated_by varchar(50), method varchar(255) not null, primary key (id)) engine=InnoDB;
create table suppliers (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), supplier_code varchar(20) not null, phone varchar(30), created_by varchar(50), updated_by varchar(50), contact_person varchar(100), email varchar(100), name varchar(150) not null, address TEXT, primary key (id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (commission_rate decimal(5,2), is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, token_version bigint not null, updated_at datetime(6), approval_status varchar(20) not null, employee_code varchar(30), phone varchar(30), created_by varchar(50), updated_by varchar(50), username varchar(50) not null, email varchar(100) not null, full_name varchar(100) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table vehicles (capacity_kg float(53), is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), status varchar(30), created_by varchar(50), updated_by varchar(50), vehicle_number varchar(50) not null, vehicle_type varchar(50), model varchar(100) not null, notes TEXT, primary key (id)) engine=InnoDB;
create table warehouses (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, record_version bigint not null, updated_at datetime(6), code varchar(20) not null, phone varchar(30), created_by varchar(50), updated_by varchar(50), contact_person varchar(100), name varchar(100) not null, address TEXT, primary key (id)) engine=InnoDB;
create index idx_audit_created on audit_logs (created_at);
create index idx_audit_entity on audit_logs (entity_name, entity_id);
create index idx_audit_module on audit_logs (module);
alter table brands add constraint UKjwckdguv8xkq16jq8tq5k3pn9 unique (code);
alter table categories add constraint UKiwylx6fb2dqdw8kfc31vaiiyp unique (code);
alter table credit_notes add constraint UKabchkricq0sc3vdu6x1eseabr unique (credit_note_number);
alter table customer_groups add constraint UKgs7w86v4nlhxsoht3e9iqgo3y unique (group_code);
alter table customers add constraint UKiqv746oh5t5is1vr4p2nl79r6 unique (customer_code);
create index idx_del_number on deliveries (delivery_number);
create index idx_del_status on deliveries (status);
create index idx_del_date on deliveries (scheduled_date);
alter table deliveries add constraint UK667lysacjsrsb1r6ppswku1rx unique (delivery_number);
create index idx_del_route_code on delivery_routes (route_code);
alter table delivery_routes add constraint UK7id1werhl73d6ni8htqpokal5 unique (route_code);
alter table document_sequences add constraint uk_doc_type_year unique (document_type, year);
alter table grns add constraint UKndpja3ldfakoiyp55yq662uq4 unique (grn_number);
alter table gtns add constraint UKhkrs58p5q79kkns8u0v11x1ct unique (gtn_number);
create index idx_inv_date on invoices (invoice_date);
create index idx_inv_status on invoices (status);
alter table invoices add constraint UKl1x55mfsay7co0r3m9ynvipd5 unique (invoice_number);
alter table journal add constraint UKsgdp7pqhyddsun65qr0bpme78 unique (source);
create index idx_pmt_date on payments (payment_date);
create index idx_pmt_customer on payments (customer_id);
create index idx_pmt_invoice on payments (invoice_id);
create index idx_pmt_status on payments (status);
create index idx_pmt_type on payments (payment_type);
alter table payments add constraint UKc6nxg52ow66u8ut91bytspy64 unique (payment_number);
alter table permissions add constraint UKpnvtwliis6p05pn6i3ndjrqt2 unique (name);
alter table prns add constraint UKsek87fwmri2hcri5au2hc38iv unique (prn_number);
alter table product_staff_quotas add constraint uk_prod_user_wh unique (product_id, user_id, warehouse_id);
create index idx_product_barcode on products (barcode);
create index idx_product_name on products (name);
alter table products add constraint UKfhmd06dsmj6k0n90swsh8ie9g unique (sku);
alter table purchase_orders add constraint UKpbiykvcpyg0jslne4gviyeuc2 unique (po_number);
create index idx_quotation_number on quotations (quotation_number);
create index idx_quotation_customer on quotations (customer_id);
create index idx_quotation_date on quotations (quotation_date);
create index idx_quotation_status on quotations (status);
alter table quotations add constraint UK9kbnjdxcf5d7qxwy80ple68bh unique (quotation_number);
alter table roles add constraint UKofx66keruapi6vyqpv6f2or37 unique (name);
alter table sales_returns add constraint UKjel0imk2fx0xg10s8hn38l712 unique (return_number);
alter table stock_adjustments add constraint UKnmisxi6vihfcie4tbnvvnaoya unique (adjustment_number);
alter table stock_balances add constraint uk_warehouse_product unique (warehouse_id, product_id);
create index idx_sm_history on stock_movements (product_id, warehouse_id, created_at);
create index idx_sm_ref on stock_movements (reference_type, reference_number);
alter table suppliers add constraint UKqlclyj0vn5vwtb86objyhmlkx unique (supplier_code);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create index idx_veh_number on vehicles (vehicle_number);
create index idx_veh_status on vehicles (status);
alter table vehicles add constraint UKpy3agdr9g5molxe2mj30p9i8i unique (vehicle_number);
alter table warehouses add constraint UK6herdbg4x5wp6gkor8epv73oc unique (code);
alter table credit_notes add constraint FK8ka4cscalb39tvpeklthke4to foreign key (customer_id) references customers (id);
alter table credit_notes add constraint FKkp7l1dshori365y0ibahfo9kl foreign key (sales_return_id) references sales_returns (id);
alter table credit_allocation add constraint FKjv72q52ejchccbyf3ox7cs31n foreign key (credit_note_id) references credit_notes (id);
alter table credit_allocation add constraint FKn27hal5oabq67wja69w4rqfhd foreign key (invoice_id) references invoices (id);
alter table customer_group_mappings add constraint FKc29qs92gwdktc5nwdih5pcnfc foreign key (group_id) references customer_groups (id);
alter table customer_group_mappings add constraint FKq5soolaa6x2jgl4fk43llc9y5 foreign key (customer_id) references customers (id);
alter table customer_groups add constraint FKnwwkhl8csbcv2pxjt98qpah15 foreign key (assigned_staff_id) references users (id);
alter table customers add constraint FK3dna0tnqmkil56f35dlq0d07g foreign key (customer_group_id) references customer_groups (id);
alter table customers add constraint FK494qka0sabp1tqip82mkh8p0d foreign key (delivery_route_id) references delivery_routes (id);
alter table deliveries add constraint FK9qtgmgbx1qu8pe9aty6ro4fiu foreign key (assistant_staff_id) references users (id);
alter table deliveries add constraint FKm4ubh4uobntck32iawsw1mlvq foreign key (driver_id) references users (id);
alter table deliveries add constraint FKidkpw02lct18cl34hfswkhdi1 foreign key (route_id) references delivery_routes (id);
alter table deliveries add constraint FKgjj47cndyarbxrqimqu8q16n8 foreign key (vehicle_id) references vehicles (id);
alter table deliveries add constraint FKio8yx4gl5y658t7b2101g3fx8 foreign key (warehouse_id) references warehouses (id);
alter table delivery_routes add constraint FKkjtd7sdebnrrt8qnpmbfi34a9 foreign key (assigned_staff_id) references users (id);
alter table grn_items add constraint FKawmvqosbaeu2en530acfpgo26 foreign key (grn_id) references grns (id);
alter table grn_items add constraint FKfjhmpfnnpo4o4aq4s19rsv94n foreign key (product_id) references products (id);
alter table grns add constraint FKhhtjlayypis01np6stgcndv3c foreign key (supplier_id) references suppliers (id);
alter table grns add constraint FK4bxwwvtky06c5fmr0sniwo6gt foreign key (warehouse_id) references warehouses (id);
alter table gtn_items add constraint FK80hcsefjjg9s2yxrvjvsbbteq foreign key (gtn_id) references gtns (id);
alter table gtn_items add constraint FK9bet6smg9t36n8avm1qaybw5h foreign key (product_id) references products (id);
alter table gtns add constraint FKsadrda2kllfd47jldu5o0bfyn foreign key (destination_warehouse_id) references warehouses (id);
alter table gtns add constraint FK5ltv1x0mqvfwk3afvts6gapn9 foreign key (source_warehouse_id) references warehouses (id);
alter table invoice_items add constraint FK46ae0lhu1oqs7cv91fn6y9n7w foreign key (invoice_id) references invoices (id);
alter table invoice_items add constraint FKs3tu9gmkgshq8oeq5n0rinxeu foreign key (product_id) references products (id);
alter table invoices add constraint FKq2w4hmh6l9othnp6cepp0cfe2 foreign key (customer_id) references customers (id);
alter table invoices add constraint FKej0v3g5mdeqisk7vps25662s4 foreign key (delivery_id) references deliveries (id);
alter table invoices add constraint FKmeucste6e5jn5xeee8atfm89h foreign key (sales_rep_id) references users (id);
alter table invoices add constraint FK2gw7glghekg32lvpmeimn0lys foreign key (warehouse_id) references warehouses (id);
alter table journal_line add constraint FK774ybwp581getocg1v5c4ss6 foreign key (account_code) references account (code);
alter table journal_line add constraint FKgkfebaaet9b5t3xmpxe7d6eto foreign key (journal_id) references journal (id);
alter table payment_allocation add constraint FK32vy68k9auc1m13jpsd0oqkr8 foreign key (invoice_id) references invoices (id);
alter table payment_allocation add constraint FKqysyku8kgydmok3p9fjuxs63u foreign key (payment_id) references payments (id);
alter table payments add constraint FK45dp0030s8e3myd8n6ky4e79g foreign key (customer_id) references customers (id);
alter table payments add constraint FKrbqec6be74wab8iifh8g3i50i foreign key (invoice_id) references invoices (id);
alter table prn_items add constraint FKser6v2unp6a2fvjxr41ib3253 foreign key (product_id) references products (id);
alter table prn_items add constraint FK9q8ajobb2uu1pgw82u8q18ehf foreign key (prn_id) references prns (id);
alter table prns add constraint FKp93vwxredeqad0aftxu8w9wus foreign key (supplier_id) references suppliers (id);
alter table prns add constraint FKtls2mbcxrbdiy4rnehwf6u509 foreign key (warehouse_id) references warehouses (id);
alter table product_staff_quotas add constraint FKtfy73kr30yumldphv20pt6k4n foreign key (product_id) references products (id);
alter table product_staff_quotas add constraint FKgxuneckmr0r9frxv7bsngxnsb foreign key (user_id) references users (id);
alter table product_staff_quotas add constraint FK46yjsl1hw85cjp10suktvlw4w foreign key (warehouse_id) references warehouses (id);
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands (id);
alter table products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
alter table products add constraint FK6i174ixi9087gcvvut45em7fd foreign key (supplier_id) references suppliers (id);
alter table products add constraint FK71egr0nqa3sut2fdk34e7o9eq foreign key (warehouse_id) references warehouses (id);
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers (id);
alter table purchase_orders add constraint FK83rqgbblncfji6cyhcqsyl8hm foreign key (warehouse_id) references warehouses (id);
alter table purchase_order_item add constraint FKppexs9b56y3dqjemtescfc3od foreign key (product_id) references products (id);
alter table purchase_order_item add constraint FKddti1rndcamtvryfvl0f3mbs2 foreign key (purchase_order_id) references purchase_orders (id);
alter table quotation_items add constraint FK3od7a9gjc2c3v9x04a41yl8kc foreign key (product_id) references products (id);
alter table quotation_items add constraint FK7y587hckcncga8qtka1i06cbp foreign key (quotation_id) references quotations (id);
alter table quotations add constraint FKbv6vp77w2lpnag5v0b8keobm9 foreign key (customer_id) references customers (id);
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references permissions (id);
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles (id);
alter table sales_return_items add constraint FK5w7uvj2my25agnw9lsuwddcna foreign key (product_id) references products (id);
alter table sales_return_items add constraint FK6bndgkqb5vxhudpbwgw74y6i8 foreign key (sales_return_id) references sales_returns (id);
alter table sales_returns add constraint FKgqee314vb7h0a950q9vjfy9ie foreign key (customer_id) references customers (id);
alter table sales_returns add constraint FK49njn3w4xc5v2x2mcg5rcvx21 foreign key (invoice_id) references invoices (id);
alter table sales_returns add constraint FKopryb4oppy1wlga8sayf7ya7n foreign key (warehouse_id) references warehouses (id);
alter table stock_adjustment_items add constraint FKhxxr5de31eri5v839hancjaky foreign key (product_id) references products (id);
alter table stock_adjustment_items add constraint FK7yqf3vpvncbr1084r1nbkjg2t foreign key (adjustment_id) references stock_adjustments (id);
alter table stock_adjustments add constraint FKrx0rcvfnre9vgtayn08ax20f5 foreign key (warehouse_id) references warehouses (id);
alter table stock_balances add constraint FK6fray4gkxr3v1oyfkaocf97b7 foreign key (product_id) references products (id);
alter table stock_balances add constraint FKnunr6oip0sfbr0v72cu5i03ip foreign key (warehouse_id) references warehouses (id);
alter table stock_movements add constraint FKjcaag8ogfjxpwmqypi1wfdaog foreign key (product_id) references products (id);
alter table stock_movements add constraint FKiparp4rp4rsfsxb9y02oyxauh foreign key (warehouse_id) references warehouses (id);
alter table supplier_payment add constraint FK583swwkjb1fw1bsm1ne7sjgns foreign key (grn_id) references grns (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
